export const alcohol = [
    // --- BOKEK (Range: < 100k) ---
    // ANGGUR & LOKAL LEGENDS
    { name: "Anggur Merah Orang Tua (Amer)", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Legendary since 1948. Teman setia saat dompet tipis.", priceRange: "Rp60.000–85.000" },
    { name: "Anggur Putih Orang Tua", category: "Alkohol", emoji: "🥂", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Lebih kalem dikit dari Amer, tapi tetep nendang.", priceRange: "Rp60.000–80.000" },
    { name: "Anggur Kolesom Orang Tua", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 17.5, desc: "Ada gingsengnya, biar kuat begadang.", priceRange: "Rp70.000–90.000" },
    { name: "Intisari Anggur Gingseng", category: "Alkohol", emoji: "🍾", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Saingan berat Amer, rasa lebih herbal.", priceRange: "Rp55.000–75.000" },
    { name: "Arak Bali (Arbal)", category: "Alkohol", emoji: "🍶", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Kearifan lokal Pulau Dewata. Keras bos.", priceRange: "Rp35.000–60.000" },
    { name: "Kawa Kawa Anggur Merah", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 19.8, desc: "Amer versi modern, rasa lebih manis.", priceRange: "Rp70.000–90.000" },
    { name: "Kawa Kawa Anggur Hijau", category: "Alkohol", emoji: "🥂", price: 1, tags: ['mabok', 'high_abv'], abv: 19.8, desc: "Seger, manis, mematikan perlahan.", priceRange: "Rp70.000–90.000" },
    { name: "Kawa Kawa Pineapple", category: "Alkohol", emoji: "🍍", price: 1, tags: ['mabok', 'high_abv'], abv: 19.8, desc: "Rasa nanas, tropical vibes tapi murah.", priceRange: "Rp70.000–90.000" },
    { name: "Anggur Merah McDonald", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Bukan punya restoran fast food, ini anggur lokal juga.", priceRange: "Rp50.000–70.000" },
    { name: "Anggur Merah Columbus", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Alternatif Amer yang lumayan oke.", priceRange: "Rp55.000–75.000" },
    { name: "Anggur Merah Gold Orang Tua", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'high_abv'], abv: 19.7, desc: "Versi premium dikit, botolnya lebih kece.", priceRange: "Rp85.000–100.000" },
    { name: "Anggur Putih McDonald", category: "Alkohol", emoji: "🥂", price: 1, tags: ['mabok', 'high_abv'], abv: 14.7, desc: "Pasangan si merah, buat yang suka lebih light.", priceRange: "Rp50.000–70.000" },
    { name: "Beras Kencur Cap Orang Tua", category: "Alkohol", emoji: "🏺", price: 1, tags: ['mabok', 'medium_abv'], abv: 14.7, desc: "Jamu atau alkohol? Dua-duanya.", priceRange: "Rp50.000–70.000" },
    { name: "Anggur Ketan Hitam Orang Tua", category: "Alkohol", emoji: "🍷", price: 1, tags: ['mabok', 'medium_abv'], abv: 14.7, desc: "Manis ketan item, enak buat angetin badan.", priceRange: "Rp60.000–80.000" },
    { name: "Ciu Bekonang", category: "Alkohol", emoji: "🍶", price: 1, tags: ['mabok', 'high_abv'], abv: 35, desc: "Legendary spirit from Solo. Keras dan panas.", priceRange: "Rp20.000–40.000" },
    { name: "Tuak Manis", category: "Alkohol", emoji: "🥥", price: 1, tags: ['mabok', 'medium_abv'], abv: 5, desc: "Hasil fermentasi nira, manis-manis memabukkan.", priceRange: "Rp10.000–20.000" },
    { name: "Soju Bae (Original)", category: "Alkohol", emoji: "🍶", price: 1, tags: ['mabok', 'medium_abv'], abv: 13, desc: "Soju lokal harga bersahabat.", priceRange: "Rp45.000–60.000" },
    { name: "Soju Bae (Lychee)", category: "Alkohol", emoji: "🍒", price: 1, tags: ['mabok', 'medium_abv'], abv: 13, desc: "Wangi leci, enak buat shot.", priceRange: "Rp45.000–60.000" },
    { name: "Soju Daebak (Original)", category: "Alkohol", emoji: "🍶", price: 1, tags: ['mabok', 'medium_abv'], abv: 19, desc: "Grandmaster soju lokal.", priceRange: "Rp50.000–65.000" },
    { name: "Soju Cham Joeun (Lime)", category: "Alkohol", emoji: "🍋", price: 1, tags: ['mabok', 'medium_abv'], abv: 16, desc: "Seger jeruk nipis, ati-ati asam lambung.", priceRange: "Rp45.000–60.000" },
    
    // BEERS & RTD (Ready To Drink)
    { name: "Bir Bintang (Botol Besar)", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.7, desc: "Kebanggaan nasional. Dingin lebih nikmat.", priceRange: "Rp35.000–45.000" },
    { name: "Bir Bintang Radler Lemon", category: "Alkohol", emoji: "🍋", price: 1, tags: ['mabok', 'low_abv'], abv: 2, desc: "Bir rasa lemon, kayak minum soda gembira.", priceRange: "Rp25.000–35.000" },
    { name: "Bir Bintang Crystal", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.3, desc: "Lebih smooth, less bitter.", priceRange: "Rp35.000–45.000" },
    { name: "Anker Beer (Botol Besar)", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Pahitnya pas, cocok buat nongkrong.", priceRange: "Rp30.000–40.000" },
    { name: "Anker Stout", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Bir hitam legendaris, pait mantap.", priceRange: "Rp35.000–45.000" },
    { name: "Guinness Smooth", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.5, desc: "Bir hitam yang nggak terlalu pait.", priceRange: "Rp40.000–50.000" },
    { name: "Prost Beer", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Bir lokal baru, rasanya ringan.", priceRange: "Rp30.000–40.000" },
    { name: "Prost Alster", category: "Alkohol", emoji: "🍋", price: 1, tags: ['mabok', 'low_abv'], abv: 2.5, desc: "Lemon beer, seger banget pas panas.", priceRange: "Rp25.000–35.000" },
    { name: "Singaraja Beer", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Birnya rakyat Bali, murah meriah.", priceRange: "Rp25.000–35.000" },
    { name: "Bali Hai Premium", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.9, desc: "Lager beer yang crisp dan refreshing.", priceRange: "Rp30.000–40.000" },
    { name: "Bali Hai Draft", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.9, desc: "Botol kecil, rasa draft beer.", priceRange: "Rp25.000–35.000" },
    { name: "Panther Stout", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.9, desc: "Bir hitam murah, nendang banget.", priceRange: "Rp35.000–45.000" },
    { name: "Mix Max Anggur", category: "Alkohol", emoji: "🍇", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Vodka mix rasa anggur, manis banget.", priceRange: "Rp25.000–35.000" },
    { name: "Mix Max Blueberry", category: "Alkohol", emoji: "🫐", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Ungu menggoda, hati-hati gula.", priceRange: "Rp25.000–35.000" },
    { name: "Mix Max Exotic Blue", category: "Alkohol", emoji: "🔵", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Warnanya biru, rasanya unik.", priceRange: "Rp25.000–35.000" },
    { name: "Smirnoff Ice Lemon", category: "Alkohol", emoji: "🍋", price: 1, tags: ['mabok', 'low_abv'], abv: 4.5, desc: "Klasik, seger, kayak sprite tapi jahat.", priceRange: "Rp30.000–40.000" },
    { name: "Smirnoff Ice Raspberry", category: "Alkohol", emoji: "🍒", price: 1, tags: ['mabok', 'low_abv'], abv: 4.5, desc: "Manis raspberry, favorit ciwi-ciwi.", priceRange: "Rp30.000–40.000" },
    { name: "Iceland Twist (Lemon)", category: "Alkohol", emoji: "🍋", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Lokal punya, rasa lemon.", priceRange: "Rp25.000–35.000" },
    { name: "Iceland Twist (Lychee)", category: "Alkohol", emoji: "🍒", price: 1, tags: ['mabok', 'low_abv'], abv: 4.8, desc: "Wangi leci, enak dingin.", priceRange: "Rp25.000–35.000" },
    { name: "Draft Beer (Kaleng)", category: "Alkohol", emoji: "🍺", price: 1, tags: ['mabok', 'low_abv'], abv: 4.9, desc: "Bir kaleng murah meriah di minimarket.", priceRange: "Rp20.000–30.000" },
    { name: "Kuda Putih", category: "Alkohol", emoji: "🐎", price: 1, tags: ['mabok', 'low_abv'], abv: 4.5, desc: "Bir lokal lawas, jarang ada tapi murah.", priceRange: "Rp25.000–35.000" },
    
    // SPIRITS (SMALL/CHEAP)
    { name: "Iceland Vodka (350ml)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Vodka lokal, cocok buat mix jus jeruk.", priceRange: "Rp75.000–95.000" },
    { name: "Iceland Vodka (250ml)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Ukuran saku, buat pemanasan.", priceRange: "Rp55.000–70.000" },
    { name: "Mansion House Whisky (350ml)", category: "Alkohol", emoji: "🥃", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Whisky-whiskian warung, lumayan anget.", priceRange: "Rp70.000–90.000" },
    { name: "Mansion House Vodka (350ml)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Temennya whisky, rasanya lebih netral.", priceRange: "Rp70.000–90.000" },
    { name: "Drum Whisky (350ml)", category: "Alkohol", emoji: "🥃", price: 1, tags: ['mabok', 'high_abv'], abv: 43, desc: "Oak aged katanya, rasanya ya gitu deh.", priceRange: "Rp75.000–95.000" },
    { name: "Topi Miring", category: "Alkohol", emoji: "🎩", price: 1, tags: ['mabok', 'high_abv'], abv: 19, desc: "Vodka legendaris bapak-bapak pos ronda.", priceRange: "Rp55.000–75.000" },
    { name: "Vibe Vodka (Mungil)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 40, desc: "Botol kecil Vibe, kalo nemu murah sikat.", priceRange: "Rp80.000–95.000" },
    { name: "Gilbey's Gin (350ml)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 37.5, desc: "Gin murah meriah buat Gin Tonic di kosan.", priceRange: "Rp85.000–99.000" },
    { name: "Gilbey's Vodka (350ml)", category: "Alkohol", emoji: "🍸", price: 1, tags: ['mabok', 'high_abv'], abv: 37.5, desc: "Vodka standar, jangan lupa mixernya.", priceRange: "Rp85.000–99.000" },
    { name: "Newport Blue", category: "Alkohol", emoji: "🔵", price: 1, tags: ['mabok', 'high_abv'], abv: 20, desc: "Minuman biru, manis, cepet naik.", priceRange: "Rp70.000–90.000" },
    { name: "Newport Passion", category: "Alkohol", emoji: "🟠", price: 1, tags: ['mabok', 'high_abv'], abv: 20, desc: "Rasa markisa, temennya yang biru.", priceRange: "Rp70.000–90.000" },

    // --- GAJIAN (Range: 100k - 500k) ---
    { name: "Smirnoff Vodka Red", category: "Alkohol", emoji: "🍸", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Vodka sejuta umat buat party.", priceRange: "Rp350.000–400.000" },
    { name: "Captain Morgan Spiced Gold", category: "Alkohol", emoji: "🏴‍☠️", price: 2, tags: ['mabok', 'high_abv'], abv: 35, desc: "Rum manis rempah, enak dicampur cola.", priceRange: "Rp350.000–450.000" },
    { name: "Captain Morgan White Rum", category: "Alkohol", emoji: "🏴‍☠️", price: 2, tags: ['mabok', 'high_abv'], abv: 37.5, desc: "Rum putih buat mojito yang lebih nendang.", priceRange: "Rp350.000–450.000" },
    { name: "Bacardi Carta Blanca", category: "Alkohol", emoji: "🦇", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "White rum wajib buat Mojito.", priceRange: "Rp380.000–450.000" },
    { name: "Gordon's Dry Gin", category: "Alkohol", emoji: "🍸", price: 2, tags: ['mabok', 'high_abv'], abv: 37.5, desc: "Gin klasik buat Gin & Tonic sore-sore.", priceRange: "Rp380.000–450.000" },
    { name: "Gordon's Pink Gin", category: "Alkohol", emoji: "🍓", price: 2, tags: ['mabok', 'high_abv'], abv: 37.5, desc: "Gin rasa berry, warnanya pink lucu.", priceRange: "Rp400.000–480.000" },
    { name: "Absolut Vodka", category: "Alkohol", emoji: "🍸", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Vodka Swedia, botolnya ikonik.", priceRange: "Rp400.000–500.000" },
    { name: "Jose Cuervo Especial Silver", category: "Alkohol", emoji: "🌵", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Tequila buat shot. Garem, lemon, telen.", priceRange: "Rp450.000–550.000" },
    { name: "Jose Cuervo Especial Gold", category: "Alkohol", emoji: "🌵", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Lebih manis dikit, ati-ati besok pusing.", priceRange: "Rp450.000–550.000" },
    { name: "Jagermeister", category: "Alkohol", emoji: "🦌", price: 2, tags: ['mabok', 'high_abv'], abv: 35, desc: "Herbal Jerman. Wajib dingin beku!", priceRange: "Rp450.000–550.000" },
    { name: "Baileys Irish Cream", category: "Alkohol", emoji: "🥛", price: 2, tags: ['mabok', 'medium_abv'], abv: 17, desc: "Krim wiski manis, enak diminum on rocks.", priceRange: "Rp450.000–550.000" },
    { name: "Soju Jinro (Original)", category: "Alkohol", emoji: "🍶", price: 2, tags: ['mabok', 'medium_abv'], abv: 17, desc: "Minuman drama Korea. Manis tapi nipu.", priceRange: "Rp100.000–120.000" },
    { name: "Soju Chum Churum (Peach)", category: "Alkohol", emoji: "🍑", price: 2, tags: ['mabok', 'medium_abv'], abv: 12, desc: "Rasa peach wangi, ciwi-ciwi suka.", priceRange: "Rp100.000–120.000" },
    { name: "Soju Good Day (Blueberry)", category: "Alkohol", emoji: "🫐", price: 2, tags: ['mabok', 'medium_abv'], abv: 13.5, desc: "Manis blueberry, hati-hati blackout.", priceRange: "Rp100.000–120.000" },
    { name: "Wine Sababay (Red/White)", category: "Alkohol", emoji: "🍷", price: 2, tags: ['mabok', 'medium_abv'], abv: 12, desc: "Wine lokal Bali, kualitas internasional.", priceRange: "Rp200.000–300.000" },
    { name: "Wine Hatten (Rose)", category: "Alkohol", emoji: "🍷", price: 2, tags: ['mabok', 'medium_abv'], abv: 11.5, desc: "Wine Bali legend, manis seger.", priceRange: "Rp180.000–250.000" },
    { name: "Black Label (Johnnie Walker)", category: "Alkohol", emoji: "🚶", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Whisky bapak-bapak mapan.", priceRange: "Rp550.000–650.000" }, 
    { name: "Red Label (Johnnie Walker)", category: "Alkohol", emoji: "🚶", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Adiknya Black Label, buat campur-campur.", priceRange: "Rp400.000–500.000" },
    { name: "Jim Beam White", category: "Alkohol", emoji: "🥃", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Bourbon Kentucky, manis vanilla.", priceRange: "Rp400.000–500.000" },
    { name: "Jack Daniel's Old No. 7", category: "Alkohol", emoji: "🥃", price: 2, tags: ['mabok', 'high_abv'], abv: 40, desc: "Tennessee Whiskey klasik, wangi oak.", priceRange: "Rp500.000–600.000" },

    // --- SULTAN (Range: > 500k/1jt++) ---
    { name: "Clase Azul Reposado", category: "Alkohol", emoji: "🔔", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Tequila botol keramik lonceng. Mahal gila.", priceRange: "Rp3.500.000++" },
    { name: "Macallan 12 Years", category: "Alkohol", emoji: "🥃", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Single malt scotch, alus banget di tenggorokan.", priceRange: "Rp1.800.000++" },
    { name: "Hennessy V.S.O.P", category: "Alkohol", emoji: "🥃", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Cognac fancy, minumnya pelan-pelan.", priceRange: "Rp1.500.000++" },
    { name: "Hibiki Harmony", category: "Alkohol", emoji: "🎎", price: 3, tags: ['mabok', 'high_abv'], abv: 43, desc: "Whisky Jepang, botolnya cantik rasanya harmonis.", priceRange: "Rp2.500.000++" },
    { name: "Yamazaki 12 Years", category: "Alkohol", emoji: "🇯🇵", price: 3, tags: ['mabok', 'high_abv'], abv: 43, desc: "Rare item Jepang, harganya gorengan.", priceRange: "Rp3.500.000++" },
    { name: "Grey Goose Vodka", category: "Alkohol", emoji: "🦢", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Vodka Prancis, smooth parah.", priceRange: "Rp700.000–900.000" },
    { name: "Belvedere Vodka", category: "Alkohol", emoji: "🍸", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Vodka Polandia, botolnya ada lampunya kadang.", priceRange: "Rp800.000–1.000.000" },
    { name: "Monkey 47 Gin", category: "Alkohol", emoji: "🐒", price: 3, tags: ['mabok', 'high_abv'], abv: 47, desc: "Gin Jerman botol kecil, rempahnya kompleks.", priceRange: "Rp900.000–1.200.000" },
    { name: "Hendrick's Gin", category: "Alkohol", emoji: "🥒", price: 3, tags: ['mabok', 'high_abv'], abv: 41.4, desc: "Gin botol obat, ada rasa timun mawarnya.", priceRange: "Rp800.000–1.000.000" },
    { name: "Don Julio 1942", category: "Alkohol", emoji: "🌵", price: 3, tags: ['mabok', 'high_abv'], abv: 38, desc: "Tequila artis, botol tinggi, rasa vanilla.", priceRange: "Rp3.000.000++" },
    { name: "Patron Silver", category: "Alkohol", emoji: "🐝", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Tequila premium, botol kotak ada lebahnya.", priceRange: "Rp900.000–1.100.000" },
    { name: "Glenfiddich 12", category: "Alkohol", emoji: "🦌", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Single malt entry level buat sultan pemula.", priceRange: "Rp900.000–1.100.000" },
    { name: "Moet & Chandon Imperial", category: "Alkohol", emoji: "🍾", price: 3, tags: ['mabok', 'low_abv'], abv: 12, desc: "Champagne buat selebrasi, pop the cork!", priceRange: "Rp1.200.000++" },
    { name: "Dom Perignon", category: "Alkohol", emoji: "🍾", price: 3, tags: ['mabok', 'low_abv'], abv: 12.5, desc: "Champagne-nya rapper dan milyarder.", priceRange: "Rp4.000.000++" },
    { name: "Martell Cordon Bleu", category: "Alkohol", emoji: "🥃", price: 3, tags: ['mabok', 'high_abv'], abv: 40, desc: "Cognac legend, wangi banget.", priceRange: "Rp3.000.000++" },
    { name: "Suntory Roku Gin", category: "Alkohol", emoji: "⬡", price: 3, tags: ['mabok', 'high_abv'], abv: 43, desc: "Gin Jepang, botol segi enam, floral.", priceRange: "Rp700.000–900.000" }
];
