export const drinks = [
    // --- MINUMAN ---
    { name: "Kopi Kenangan Mantan", category: "Minuman", emoji: "☕", price: 2, tags: [], desc: "Kopi susu gula aren kekinian.", priceRange: "Rp18.000–25.000" },
    { name: "Kopi Susu Gula Aren", category: "Minuman", emoji: "☕", price: 1, tags: [], desc: "Kopi susu standar anak senja.", priceRange: "Rp15.000–20.000" },
    { name: "Cappuccino", category: "Minuman", emoji: "☕", price: 2, tags: [], desc: "Foam susunya tebel.", priceRange: "Rp25.000–40.000" },
    { name: "Americano", category: "Minuman", emoji: "☕", price: 2, tags: [], desc: "Kopi item encer tanpa gula.", priceRange: "Rp20.000–35.000" },
    { name: "Boba Brown Sugar", category: "Minuman", emoji: "🧋", price: 2, tags: [], desc: "Kenyal manis, hati-hati kalori.", priceRange: "Rp25.000–40.000" },
    { name: "Thai Tea", category: "Minuman", emoji: "🧋", price: 1, tags: [], desc: "Teh oren manis susu kental manis.", priceRange: "Rp10.000–20.000" },
    { name: "Green Tea Latte", category: "Minuman", emoji: "🍵", price: 2, tags: [], desc: "Matcha susu yang creamy.", priceRange: "Rp25.000–40.000" },
    { name: "Teh Tarik", category: "Minuman", emoji: "☕", price: 1, tags: [], desc: "Teh susu ditarik-tarik biar berbusa.", priceRange: "Rp10.000–15.000" },
    { name: "Wedang Ronde", category: "Minuman", emoji: "🥣", price: 1, tags: ['sehat'], desc: "Jahe anget ada bola-bola ketannya.", priceRange: "Rp8.000–12.000" },
    { name: "Bajigur", category: "Minuman", emoji: "☕", price: 1, tags: [], desc: "Santan gula jawa anget.", priceRange: "Rp5.000–10.000" },
    { name: "Bandrek", category: "Minuman", emoji: "☕", price: 1, tags: ['sehat'], desc: "Jahe merah pedes anget.", priceRange: "Rp5.000–10.000" },
    { name: "Soda Gembira", category: "Minuman", emoji: "🥤", price: 1, tags: [], desc: "Soda susu sirup merah, bikin hepi.", priceRange: "Rp12.000–18.000" },
    { name: "Air Mineral", category: "Minuman", emoji: "💧", price: 1, tags: ['sehat'], desc: "Paling sehat, paling murah, wajib.", priceRange: "Rp3.000–5.000" },
    { name: "Susu Jahe", category: "Minuman", emoji: "🥛", price: 1, tags: ['sehat'], desc: "Susu kental manis pake jahe geprek.", priceRange: "Rp8.000–12.000" },
    { name: "Lemon Tea", category: "Minuman", emoji: "🍋", price: 1, tags: ['sehat'], desc: "Teh asem seger.", priceRange: "Rp5.000–10.000" },
    { name: "Milkshake Coklat", category: "Minuman", emoji: "🥤", price: 2, tags: [], desc: "Susu es krim blender, kental manis.", priceRange: "Rp20.000–35.000" },
    { name: "Es Oyen", category: "Minuman", emoji: "🍧", price: 1, tags: [], desc: "Es campur khas Bandung.", priceRange: "Rp10.000–15.000" },
    { name: "Sop Buah", category: "Minuman", emoji: "🍧", price: 2, tags: ['sehat'], desc: "Potongan buah segar dalam kuah susu.", priceRange: "Rp15.000–25.000" },
    { name: "Es Kuwut", category: "Minuman", emoji: "🍈", price: 1, tags: ['sehat'], desc: "Es kelapa melon jeruk nipis khas Bali.", priceRange: "Rp10.000–15.000" },
    { name: "Liang Teh", category: "Minuman", emoji: "🍵", price: 1, tags: ['sehat'], desc: "Teh herbal buat panas dalem.", priceRange: "Rp5.000–8.000" },
    { name: "Kopi Tubruk", category: "Minuman", emoji: "☕", price: 1, tags: [], desc: "Kopi hitam ada ampasnya, strong.", priceRange: "Rp5.000–10.000" },
    { name: "Vietnam Drip", category: "Minuman", emoji: "☕", price: 2, tags: [], desc: "Kopi tetes pake susu kental manis.", priceRange: "Rp15.000–25.000" },
    { name: "Mango Sago", category: "Minuman", emoji: "🥭", price: 2, tags: [], desc: "Dessert mangga sagu creamy.", priceRange: "Rp20.000–35.000" },
    { name: "Es Pisang Ijo", category: "Minuman", emoji: "🍧", price: 1, tags: [], desc: "Pisang balut tepung ijo bubur sumsum.", priceRange: "Rp12.000–20.000" },
    { name: "Bir Pletok", category: "Minuman", emoji: "🍺", price: 1, tags: ['sehat'], desc: "Nggak mabok, isinya rempah betawi.", priceRange: "Rp10.000–15.000" },
    { name: "Jus Sirsak", category: "Minuman", emoji: "🥤", price: 1, tags: ['sehat'], desc: "Asem manis putih kental.", priceRange: "Rp10.000–15.000" },
    { name: "Es Kacang Merah", category: "Minuman", emoji: "🍧", price: 2, tags: [], desc: "Kacang merah empuk manis es serut.", priceRange: "Rp15.000–25.000" },
    { name: "Yoghurt Drink", category: "Minuman", emoji: "🥤", price: 2, tags: ['sehat'], desc: "Asam seger baik buat perut.", priceRange: "Rp15.000–25.000" },
    { name: "Matcha Cheese Tea", category: "Minuman", emoji: "🍵", price: 2, tags: [], desc: "Teh hijau topping keju asin.", priceRange: "Rp25.000–40.000" },
    { name: "Dalgona Coffee", category: "Minuman", emoji: "☕", price: 2, tags: [], desc: "Sempet viral, foam kopi di atas susu.", priceRange: "Rp20.000–30.000" }
];
