export const foods = [
    // --- NASI ---
    { name: "Nasi Goreng Spesial", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Menu andalan segala umat, telurnya tumpeh-tumpeh.", priceRange: "Rp15.000–25.000" },
    { name: "Nasi Goreng Gila", category: "Nasi", emoji: "🍛", price: 1, tags: ['pedas'], desc: "Isian sosis baksonya nggak ngotak, pedesnya nampol!", priceRange: "Rp18.000–28.000" },
    { name: "Nasi Goreng Kambing", category: "Nasi", emoji: "🍛", price: 2, tags: [], desc: "Aroma rempahnya bikin laper sekecamatan.", priceRange: "Rp30.000–50.000" },
    { name: "Nasi Goreng Seafood", category: "Nasi", emoji: "🍤", price: 2, tags: [], desc: "Mewah dikit, ada udang sama cumi ngumpet.", priceRange: "Rp25.000–45.000" },
    { name: "Nasi Goreng Jawa", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Manis gurih, bumbunya medok banget.", priceRange: "Rp15.000–22.000" },
    { name: "Nasi Goreng Mawut", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Campuran nasi sama mie, karbo loading maksimal.", priceRange: "Rp15.000–20.000" },
    { name: "Nasi Goreng Pete", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Bau tapi nagih, siap-siap sikat gigi abis ini.", priceRange: "Rp18.000–25.000" },
    { name: "Nasi Goreng Ikan Asin", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Asin gurihnya bikin nambah nasi terus.", priceRange: "Rp18.000–25.000" },
    { name: "Nasi Padang Rendang", category: "Nasi", emoji: "🍛", price: 2, tags: [], desc: "Raja segala makanan, bumbunya nendang abis.", priceRange: "Rp25.000–40.000" },
    { name: "Nasi Padang Ayam Pop", category: "Nasi", emoji: "🍗", price: 2, tags: [], desc: "Ayam pucat tapi rasanya nggak main-main.", priceRange: "Rp25.000–35.000" },
    { name: "Nasi Padang Tunjang", category: "Nasi", emoji: "🥩", price: 2, tags: [], desc: "Kenyal-kenyal gurih, kolesterolnya dipikir nanti aja.", priceRange: "Rp30.000–45.000" },
    { name: "Nasi Padang Dendeng", category: "Nasi", emoji: "🥩", price: 2, tags: ['pedas'], desc: "Kriuk-kriuk pedes balado, mantap jiwa.", priceRange: "Rp25.000–40.000" },
    { name: "Nasi Padang Otak-otak", category: "Nasi", emoji: "🐟", price: 2, tags: [], desc: "Lembut gurih, kuah gulainya banjir.", priceRange: "Rp20.000–30.000" },
    { name: "Nasi Uduk Komplit", category: "Nasi", emoji: "🍚", price: 1, tags: [], desc: "Sarapan atau makan malam tetep masuk, harum santannya juara.", priceRange: "Rp12.000–20.000" },
    { name: "Nasi Kuning", category: "Nasi", emoji: "🟡", price: 1, tags: [], desc: "Warna cerah buat hari yang cerah (semoga).", priceRange: "Rp10.000–18.000" },
    { name: "Nasi Campur Warteg", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Menu random sesuai mood mbaknya, murah meriah.", priceRange: "Rp15.000–25.000" },
    { name: "Nasi Liwet", category: "Nasi", emoji: "🍚", price: 1, tags: [], desc: "Gurihnya nasi dimasak pake santan & rempah.", priceRange: "Rp20.000–35.000" },
    { name: "Nasi Timbel", category: "Nasi", emoji: "🍃", price: 2, tags: ['sehat'], desc: "Makan di daun pisang rasanya jadi 2x lipat lebih enak.", priceRange: "Rp25.000–40.000" },
    { name: "Nasi Bakar Ayam", category: "Nasi", emoji: "🔥", price: 1, tags: [], desc: "Wangi daun pisang kebakar itu lho, beuh!", priceRange: "Rp15.000–25.000" },
    { name: "Nasi Bakar Teri", category: "Nasi", emoji: "🔥", price: 1, tags: [], desc: "Gurih asin teri medan, sederhana tapi nikmat.", priceRange: "Rp15.000–22.000" },
    { name: "Nasi Hainam", category: "Nasi", emoji: "🍗", price: 2, tags: [], desc: "Ayam rebus jahe yang lembut banget.", priceRange: "Rp35.000–50.000" },
    { name: "Nasi Gila", category: "Nasi", emoji: "🍛", price: 1, tags: ['pedas'], desc: "Toppingnya tumpeh-tumpeh, rasanya gila beneran.", priceRange: "Rp18.000–25.000" },
    { name: "Nasi Kulit Syuurga", category: "Nasi", emoji: "🐔", price: 1, tags: [], desc: "Kulit ayam krispi yang bikin lupa diet.", priceRange: "Rp18.000–25.000" },
    { name: "Nasi Bebek Madura", category: "Nasi", emoji: "🦆", price: 2, tags: ['pedas'], desc: "Bumbu hitamnya itu lho, pedes gurih nagih!", priceRange: "Rp25.000–40.000" },
    { name: "Nasi Pecel Madiun", category: "Nasi", emoji: "🥗", price: 1, tags: ['sehat', 'pedas'], desc: "Sayur mayur siram bumbu kacang, sehat tapi enak.", priceRange: "Rp12.000–20.000" },
    { name: "Nasi Krawu", category: "Nasi", emoji: "🥩", price: 2, tags: [], desc: "Khas Gresik, daging suwirnya manis gurih.", priceRange: "Rp25.000–35.000" },
    { name: "Nasi Kapau", category: "Nasi", emoji: "🍛", price: 2, tags: [], desc: "Versi upgrade Nasi Padang, lauknya lebih barbar.", priceRange: "Rp30.000–50.000" },
    { name: "Nasi Bogana", category: "Nasi", emoji: "🍃", price: 2, tags: [], desc: "Nasi rames khas Tegal dibungkus daun pisang.", priceRange: "Rp20.000–30.000" },
    { name: "Nasi Megono", category: "Nasi", emoji: "🍃", price: 1, tags: ['sehat'], desc: "Nangka muda cincang yang unik banget rasanya.", priceRange: "Rp10.000–18.000" },
    { name: "Nasi Tutug Oncom", category: "Nasi", emoji: "🍛", price: 1, tags: [], desc: "Nasi campur oncom bakar, wangi kencurnya khas.", priceRange: "Rp15.000–25.000" },
    { name: "Nasi Kucing", category: "Nasi", emoji: "🐱", price: 1, tags: [], desc: "Porsi dikit, tapi makannya 5 bungkus.", priceRange: "Rp3.000–5.000" },
    { name: "Rice Bowl Teriyaki", category: "Nasi", emoji: "🍱", price: 2, tags: [], desc: "Praktis, manis gurih, kenyang.", priceRange: "Rp25.000–40.000" },
    { name: "Rice Bowl Yakiniku", category: "Nasi", emoji: "🍱", price: 2, tags: [], desc: "Daging iris tipis bumbu bakar jepang.", priceRange: "Rp25.000–40.000" },
    { name: "Nasi Tim Ayam", category: "Nasi", emoji: "🍚", price: 1, tags: ['sehat'], desc: "Lembut, anget, cocok pas lagi nggak enak badan.", priceRange: "Rp18.000–28.000" },
    { name: "Nasi Gandul", category: "Nasi", emoji: "🥩", price: 2, tags: [], desc: "Kuah manis gurih khas Pati, dagingnya empuk.", priceRange: "Rp25.000–35.000" },

    // --- MIE & BAKSO ---
    { name: "Mie Ayam Gerobak", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Mie ayam abang-abang emang nggak ada lawan.", priceRange: "Rp12.000–18.000" },
    { name: "Mie Ayam Yamin", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Manis gurih kecap, pas banget sama kuah pisah.", priceRange: "Rp15.000–22.000" },
    { name: "Mie Goreng Tek-tek", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Suara wajan abangnya aja udah bikin laper.", priceRange: "Rp15.000–20.000" },
    { name: "Mie Aceh Goreng", category: "Mie", emoji: "🍝", price: 2, tags: ['pedas'], desc: "Rempah kuat, pedas nendang, pake acar bawang.", priceRange: "Rp25.000–40.000" },
    { name: "Mie Celor", category: "Mie", emoji: "🍜", price: 2, tags: [], desc: "Kuah santan udang yang kental dan creamy.", priceRange: "Rp20.000–35.000" },
    { name: "Mie Kocok Bandung", category: "Mie", emoji: "🍜", price: 2, tags: [], desc: "Kikilnya kenyal, kuahnya kaldu sapi banget.", priceRange: "Rp25.000–40.000" },
    { name: "Bakso Kuah Polos", category: "Bakso", emoji: "🥣", price: 1, tags: [], desc: "Simpel, anget, dagingnya berasa.", priceRange: "Rp15.000–25.000" },
    { name: "Bakso Malang Komplit", category: "Bakso", emoji: "🥣", price: 1, tags: [], desc: "Ada pangsit, bakwan, tahu, rame rasanya.", priceRange: "Rp18.000–30.000" },
    { name: "Bakso Bakar", category: "Bakso", emoji: "🍡", price: 1, tags: [], desc: "Bakso dibakar pake bumbu kecap pedas.", priceRange: "Rp15.000–25.000" },
    { name: "Bakso Urat", category: "Bakso", emoji: "🥣", price: 1, tags: [], desc: "Tekstur kasarnya itu yang bikin kangen.", priceRange: "Rp18.000–28.000" },
    { name: "Bakso Telur", category: "Bakso", emoji: "🥣", price: 1, tags: [], desc: "Surprise telur ayam utuh di dalem bakso.", priceRange: "Rp18.000–28.000" },
    { name: "Bakso Mercon", category: "Bakso", emoji: "🔥", price: 1, tags: ['pedas'], desc: "Isinya cabe rawit, siap-siap meledak!", priceRange: "Rp18.000–28.000" },
    { name: "Bakmi Jawa Godog", category: "Mie", emoji: "🍜", price: 1, tags: ['sehat'], desc: "Kuah telur bebek yang creamy alami.", priceRange: "Rp18.000–28.000" },
    { name: "Bakmi Jawa Goreng", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Masak pake arang, aromanya beda.", priceRange: "Rp18.000–28.000" },
    { name: "Kwetiau Goreng", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Kenyal-kenyal berminyak yang nikmat.", priceRange: "Rp18.000–28.000" },
    { name: "Kwetiau Siram Sapi", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Kuah kental gurih, daging sapinya empuk.", priceRange: "Rp20.000–35.000" },
    { name: "Kwetiau Bun", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Nyemek-nyemek basah, bumbunya meresap.", priceRange: "Rp20.000–35.000" },
    { name: "Bihun Goreng", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Ringan tapi ngenyangin, cocok buat makan malem.", priceRange: "Rp15.000–25.000" },
    { name: "Bihun Kuah", category: "Mie", emoji: "🍜", price: 1, tags: ['sehat'], desc: "Seger, ringan, nggak bikin begah.", priceRange: "Rp15.000–25.000" },
    { name: "Soto Mie Bogor", category: "Soto", emoji: "🍜", price: 1, tags: [], desc: "Perpaduan soto, mie, dan risoles yang unik.", priceRange: "Rp18.000–28.000" },
    { name: "Indomie Goreng Double", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Satu kurang, dua kebanyakan (tapi abis juga).", priceRange: "Rp10.000–15.000" },
    { name: "Indomie Rebus Telur", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Makanan ternyaman pas ujan.", priceRange: "Rp10.000–15.000" },
    { name: "Cwie Mie Malang", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Ayam cincang halus plus pangsit mangkok.", priceRange: "Rp18.000–28.000" },
    { name: "Lomie Kangkung", category: "Mie", emoji: "🍜", price: 2, tags: [], desc: "Kuah ebi kental yang khas banget.", priceRange: "Rp25.000–35.000" },
    { name: "Ifumie", category: "Mie", emoji: "🍝", price: 2, tags: [], desc: "Mie digoreng kering disiram capcay. Kriuk basah!", priceRange: "Rp30.000–45.000" },
    { name: "Mie Balap", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Sarapan kilat khas Medan, pedes gurih.", priceRange: "Rp10.000–15.000" },
    { name: "Mie Gomak", category: "Mie", emoji: "🍝", price: 1, tags: [], desc: "Spaghetti Batak, bumbu andaliman yang getir nikmat.", priceRange: "Rp12.000–20.000" },
    { name: "Mie Kangkung", category: "Mie", emoji: "🍜", price: 1, tags: ['sehat'], desc: "Manis gurih kuah kental dengan kangkung segar.", priceRange: "Rp20.000–30.000" },
    { name: "Mie Dok-dok", category: "Mie", emoji: "🍜", price: 1, tags: [], desc: "Mie kuah kental ala burjo, penyelamat akhir bulan.", priceRange: "Rp10.000–15.000" },
    { name: "Bakso Aci", category: "Bakso", emoji: "🥣", price: 1, tags: ['pedas'], desc: "Kenyal, pedes, asem, seger banget!", priceRange: "Rp15.000–25.000" },

    // --- SOTO & SOP ---
    { name: "Soto Ayam Ambengan", category: "Soto", emoji: "🥣", price: 1, tags: ['sehat'], desc: "Kuah kuning bening, koya-nya jangan lupa!", priceRange: "Rp15.000–25.000" },
    { name: "Soto Betawi Santan", category: "Soto", emoji: "🥣", price: 2, tags: [], desc: "Creamy santan/susu, dagingnya empuk.", priceRange: "Rp30.000–50.000" },
    { name: "Soto Lamongan", category: "Soto", emoji: "🥣", price: 1, tags: [], desc: "Soto ayam kampung yang gurihnya pas.", priceRange: "Rp18.000–28.000" },
    { name: "Soto Kudus", category: "Soto", emoji: "🥣", price: 1, tags: [], desc: "Soto mungil pake mangkok kecil, daging kerbau/ayam.", priceRange: "Rp15.000–25.000" },
    { name: "Soto Padang", category: "Soto", emoji: "🥣", price: 2, tags: [], desc: "Daging dendeng garing di dalem kuah soto.", priceRange: "Rp25.000–40.000" },
    { name: "Soto Banjar", category: "Soto", emoji: "🥣", price: 2, tags: [], desc: "Wangi rempah kayu manis & perkedel.", priceRange: "Rp25.000–40.000" },
    { name: "Coto Makassar", category: "Soto", emoji: "🥣", price: 2, tags: [], desc: "Kuah kental kacang, daging jeroan mantap.", priceRange: "Rp30.000–50.000" },
    { name: "Pallubasa", category: "Soto", emoji: "🥣", price: 2, tags: [], desc: "Mirip Coto tapi pake kelapa sangrai, gurih abis.", priceRange: "Rp30.000–50.000" },
    { name: "Sop Buntut Bakar", category: "Sop", emoji: "🥣", price: 2, tags: ['sehat'], desc: "Mewah, daging copot dari tulang, kuah seger.", priceRange: "Rp50.000–80.000" },
    { name: "Sop Iga Sapi", category: "Sop", emoji: "🥣", price: 2, tags: ['sehat'], desc: "Nyerep sumsum tulang iga, nikmat tiada tara.", priceRange: "Rp40.000–70.000" },
    { name: "Sop Ayam Pak Min", category: "Sop", emoji: "🥣", price: 1, tags: ['sehat'], desc: "Kaldu ayam kampung asli, obat flu paling enak.", priceRange: "Rp20.000–30.000" },
    { name: "Rawon Setan", category: "Sop", emoji: "⬛", price: 2, tags: [], desc: "Kuah hitam kluwek, daging empuk, toge pendek.", priceRange: "Rp25.000–45.000" },
    { name: "Tongseng Kambing", category: "Sop", emoji: "🐐", price: 2, tags: ['pedas'], desc: "Gulai tapi lebih tajam dan ada manis-manisnya.", priceRange: "Rp30.000–50.000" },
    { name: "Gulai Kambing", category: "Sop", emoji: "🐐", price: 2, tags: [], desc: "Kuah santan kuning kental, dagingnya lembut.", priceRange: "Rp30.000–50.000" },
    { name: "Sayur Asem Jakarta", category: "Sayur", emoji: "🌽", price: 1, tags: ['sehat'], desc: "Asem seger, pas banget sama ikan asin.", priceRange: "Rp10.000–15.000" },
    { name: "Sayur Lodeh", category: "Sayur", emoji: "🥥", price: 1, tags: ['sehat'], desc: "Gurih santan dengan nangka muda & labu.", priceRange: "Rp10.000–15.000" },
    { name: "Empal Gentong", category: "Sop", emoji: "🥩", price: 2, tags: [], desc: "Gulai daging sapi khas Cirebon, dimasak di gentong.", priceRange: "Rp25.000–40.000" },
    { name: "Sop Konro", category: "Sop", emoji: "🥩", price: 2, tags: [], desc: "Iga sapi raksasa kuah hitam khas Makassar.", priceRange: "Rp40.000–70.000" },
    { name: "Sop Kaki Kambing", category: "Sop", emoji: "🐐", price: 2, tags: [], desc: "Kuah susu minyak samin, kolesterol? Lupa dulu.", priceRange: "Rp35.000–60.000" },
    { name: "Tekwan", category: "Sop", emoji: "🐟", price: 1, tags: ['sehat'], desc: "Sop bakso ikan khas Palembang, seger bengkoang.", priceRange: "Rp15.000–25.000" },

    // --- AYAM & BEBEK & IKAN ---
    { name: "Ayam Geprek Bensu-level", category: "Ayam", emoji: "🌶️", price: 1, tags: ['pedas'], desc: "Ayam krispi dihancurin sambel bawang, pedes mampus.", priceRange: "Rp15.000–25.000" },
    { name: "Ayam Penyet Surabaya", category: "Ayam", emoji: "🍗", price: 1, tags: ['pedas'], desc: "Ayam goreng penyet sambel terasi, lalapan segar.", priceRange: "Rp18.000–28.000" },
    { name: "Ayam Bakar Madu", category: "Ayam", emoji: "🍗", price: 1, tags: [], desc: "Manis legit sampai ke tulang.", priceRange: "Rp18.000–28.000" },
    { name: "Ayam Goreng Lengkuas", category: "Ayam", emoji: "🍗", price: 1, tags: [], desc: "Serundeng lengkuasnya enak banget dicampur nasi.", priceRange: "Rp18.000–28.000" },
    { name: "Ayam Betutu Gilimanuk", category: "Ayam", emoji: "🍗", price: 2, tags: ['pedas'], desc: "Bumbu rempah Bali yang meresap sempurna.", priceRange: "Rp35.000–60.000" },
    { name: "Ayam Taliwang", category: "Ayam", emoji: "🌶️", price: 2, tags: ['pedas'], desc: "Ayam kampung bakar pedas khas Lombok.", priceRange: "Rp40.000–70.000" },
    { name: "Ayam Rica-rica", category: "Ayam", emoji: "🌶️", price: 1, tags: ['pedas'], desc: "Pedes jahe kemangi khas Manado.", priceRange: "Rp20.000–35.000" },
    { name: "Bebek Goreng H. Slamet", category: "Bebek", emoji: "🦆", price: 2, tags: [], desc: "Bebek garing, sambel koreknya nampol.", priceRange: "Rp30.000–50.000" },
    { name: "Bebek Bakar Kecap", category: "Bebek", emoji: "🦆", price: 2, tags: [], desc: "Daging bebek empuk dengan bumbu bakaran manis.", priceRange: "Rp30.000–50.000" },
    { name: "Pecel Lele Lamongan", category: "Ikan", emoji: "🐟", price: 1, tags: [], desc: "Lele garing + sambel terasi + nasi uduk = surga.", priceRange: "Rp15.000–22.000" },
    { name: "Ikan Bakar Cianjur", category: "Ikan", emoji: "🐟", price: 2, tags: ['sehat'], desc: "Ikan gurame bakar manis, cocok makan tengah.", priceRange: "Rp50.000–100.000" },
    { name: "Ikan Pesmol", category: "Ikan", emoji: "🐟", price: 2, tags: [], desc: "Bumbu kuning asem seger khas Sunda.", priceRange: "Rp30.000–50.000" },
    { name: "Pepes Ikan Mas", category: "Ikan", emoji: "🐟", price: 2, tags: ['sehat'], desc: "Dikukus pake daun pisang, duri lunak lebih enak.", priceRange: "Rp20.000–35.000" },
    { name: "Mangut Lele", category: "Ikan", emoji: "🐟", price: 1, tags: ['pedas'], desc: "Lele asap kuah santan pedas khas Jogja.", priceRange: "Rp15.000–25.000" },
    { name: "Ayam Tangkap", category: "Ayam", emoji: "🍗", price: 2, tags: [], desc: "Ayam goreng rempah daun kari khas Aceh.", priceRange: "Rp25.000–40.000" },
    { name: "Ayam Kalasan", category: "Ayam", emoji: "🍗", price: 1, tags: [], desc: "Ayam goreng manis gurih khas Jawa.", priceRange: "Rp20.000–30.000" },
    { name: "Sate Lilit", category: "Ikan", emoji: "🍢", price: 1, tags: [], desc: "Sate daging cincang khas Bali, wangi sereh.", priceRange: "Rp20.000–35.000" },
    { name: "Gurame Asam Manis", category: "Ikan", emoji: "🐟", price: 2, tags: [], desc: "Klasik, garing, saus merah merona.", priceRange: "Rp50.000–90.000" },
    { name: "Udang Saus Padang", category: "Seafood", emoji: "🍤", price: 2, tags: ['pedas'], desc: "Pedas, manis, gurih, jari auto dijilat.", priceRange: "Rp40.000–70.000" },
    { name: "Kepiting Lada Hitam", category: "Seafood", emoji: "🦀", price: 2, tags: ['pedas'], desc: "Makan ribet tapi worth it banget.", priceRange: "Rp80.000–150.000" },
    { name: "Cumi Goreng Tepung", category: "Seafood", emoji: "🦑", price: 2, tags: [], desc: "Kriuk-kriuk kenyal, dicocol saus sambal.", priceRange: "Rp30.000–50.000" },
    { name: "Kerang Dara Rebus", category: "Seafood", emoji: "🐚", price: 1, tags: ['sehat'], desc: "Cocol saus nanas kacang, seger.", priceRange: "Rp20.000–35.000" },
    { name: "Ayam Popcorn", category: "Ayam", emoji: "🍿", price: 1, tags: [], desc: "Cemilan ayam sekali hap.", priceRange: "Rp15.000–25.000" },
    { name: "Sayap Ayam Pedas", category: "Ayam", emoji: "🍗", price: 2, tags: ['pedas'], desc: "Makan belepotan tapi nagih.", priceRange: "Rp30.000–50.000" },
    { name: "Dori Katsu", category: "Ikan", emoji: "🐟", price: 2, tags: [], desc: "Ikan lembut tepung roti krispi.", priceRange: "Rp30.000–45.000" },

    // --- WESTERN & FAST FOOD ---
    { name: "Fried Chicken Paket Nasi", category: "Fast Food", emoji: "🍗", price: 1, tags: [], desc: "Kulitnya adalah bagian terbaik.", priceRange: "Rp15.000–25.000" },
    { name: "Burger Beef Cheese", category: "Fast Food", emoji: "🍔", price: 2, tags: [], desc: "Daging tebal, keju meleleh, mantap.", priceRange: "Rp35.000–60.000" },
    { name: "Pizza Pepperoni", category: "Western", emoji: "🍕", price: 2, tags: [], desc: "Buat sharing (atau abisin sendiri boleh juga).", priceRange: "Rp50.000–100.000" },
    { name: "Spaghetti Bolognese", category: "Western", emoji: "🍝", price: 2, tags: [], desc: "Saus daging tomat klasik yang nggak pernah salah.", priceRange: "Rp30.000–50.000" },
    { name: "Spaghetti Carbonara", category: "Western", emoji: "🍝", price: 2, tags: [], desc: "Creamy, cheesy, awas eneg kalo kebanyakan.", priceRange: "Rp35.000–55.000" },
    { name: "Spaghetti Aglio Olio", category: "Western", emoji: "🍝", price: 2, tags: ['pedas'], desc: "Simpel, bawang putih & cabe, berminyak nikmat.", priceRange: "Rp30.000–50.000" },
    { name: "Steak Sirloin", category: "Western", emoji: "🥩", price: 2, tags: [], desc: "Daging sapi panggang, juicy abis.", priceRange: "Rp80.000–150.000" },

    // --- NON-HALAL (BABI) - EXPANDED ---
    { name: "Nasi Hainam Babi", category: "Nasi", emoji: "🐷", price: 2, tags: ['non-halal'], desc: "Nasi hainam wangi dengan topping charsiu & siobak.", priceRange: "Rp40.000–60.000" },
    { name: "Babi Kriuk / Siobak", category: "Daging", emoji: "🐷", price: 2, tags: ['non-halal'], desc: "Kulitnya garing, dagingnya juicy. Surga dunia.", priceRange: "Rp50.000–80.000" },
    { name: "Babi Panggang Merah", category: "Daging", emoji: "🐷", price: 2, tags: ['non-halal'], desc: "Manis gurih, merah merona, empuk banget.", priceRange: "Rp40.000–70.000" },
    { name: "Babi Kecap", category: "Daging", emoji: "🐷", price: 2, tags: ['non-halal'], desc: "Masakan rumahan yang ngangenin, kuahnya kental.", priceRange: "Rp35.000–60.000" },
    { name: "Babi Hong", category: "Daging", emoji: "🐷", price: 2, tags: ['non-halal'], desc: "Sayur asin dan samcan yang dimasak lama, lembut parah.", priceRange: "Rp60.000–100.000" },
    { name: "Sate Babi", category: "Sate", emoji: "🍢", price: 1, tags: ['non-halal'], desc: "Daging manis gurih dibakar arang, lemaknya lumer.", priceRange: "Rp5.000–8.000/tusuk" },
    { name: "Bakut Teh", category: "Sop", emoji: "🍲", price: 2, tags: ['non-halal', 'sehat'], desc: "Kuah herbal lada yang angetin badan.", priceRange: "Rp50.000–80.000" },
    { name: "Babi Tore", category: "Daging", emoji: "🐷", price: 2, tags: ['non-halal', 'pedas'], desc: "Babi goreng garing khas Manado, cocol sambel.", priceRange: "Rp40.000–70.000" },
    { name: "Nasi Campur Kencana", category: "Nasi", emoji: "🍛", price: 2, tags: ['non-halal'], desc: "Legend banget, isiannya melimpah ruah.", priceRange: "Rp60.000–90.000" },
    { name: "Lapchiong", category: "Lauk", emoji: "🌭", price: 1, tags: ['non-halal'], desc: "Sosis babi manis, enak buat temen nasi goreng.", priceRange: "Rp10.000–20.000" },
    { name: "Sekba / Bektim", category: "Sop", emoji: "🥣", price: 1, tags: ['non-halal'], desc: "Jeroan babi kuah kecap, kenyal-kenyal sedap.", priceRange: "Rp20.000–35.000" },

    // --- VARIANT INDOMIE (ANAK KOS) - EXPANDED ---
    { name: "Indomie Goreng Original", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Makanan kebangsaan, nggak ada obat.", priceRange: "Rp3.500 (Masak Sendiri)" },
    { name: "Indomie Goreng Telur", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Upgrade dikit pake telur, kenyang maksimal.", priceRange: "Rp5.500 (Masak Sendiri)" },
    { name: "Indomie Goreng Kornet", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Mewah ala warkop, gurih kornetnya dapet.", priceRange: "Rp8.000 (Masak Sendiri)" },
    { name: "Indomie Goreng Keju", category: "Mie", emoji: "🧀", price: 1, tags: ['masak'], desc: "Creamy asin gurih, agak fancy dikit.", priceRange: "Rp7.000 (Masak Sendiri)" },
    { name: "Indomie Kuah Soto", category: "Mie", emoji: "🍜", price: 1, tags: ['masak', 'berkuah'], desc: "Seger, apalagi dikasih jeruk nipis & cabe.", priceRange: "Rp3.500 (Masak Sendiri)" },
    { name: "Indomie Kuah Kari Ayam", category: "Mie", emoji: "🍜", price: 1, tags: ['masak', 'berkuah'], desc: "Kuah kental berempah, anget di perut.", priceRange: "Rp3.500 (Masak Sendiri)" },
    { name: "Indomie Nyemek", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Kuah dikit, bumbu meresap, telur orak-arik.", priceRange: "Rp6.000 (Masak Sendiri)" },
    { name: "Indomie Dokdok", category: "Mie", emoji: "🍜", price: 1, tags: ['masak'], desc: "Ala burjo, kuah kental manis gurih.", priceRange: "Rp10.000 (Beli) / Rp5.000 (Masak)" },
    { name: "Indomie Jumbo", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Satu kurang dua kebanyakan? Enggak, ini pas.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Indomie Aceh", category: "Mie", emoji: "🍝", price: 1, tags: ['masak', 'pedas'], desc: "Rempahnya kuat, pedesnya nampol, mie-nya tebel.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Indomie Seblak", category: "Mie", emoji: "🍜", price: 1, tags: ['masak', 'pedas'], desc: "Kuah merah kencur, nggak perlu ngulek bumbu.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Indomie Hype Abis", category: "Mie", emoji: "🔥", price: 1, tags: ['masak', 'pedas'], desc: "Ayam geprek pedes mampus, siapin susu.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Indomie Salted Egg", category: "Mie", emoji: "🥚", price: 1, tags: ['masak'], desc: "Creamy telur asin, sempet hits pada masanya.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Indomie Rendang", category: "Mie", emoji: "🍝", price: 1, tags: ['masak'], desc: "Bumbu rendangnya berasa banget, wajib coba.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Indomie Rawon", category: "Mie", emoji: "⬛", price: 1, tags: ['masak'], desc: "Kuah hitam gurih, rasa daging sapinya dapet.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Indomie Cabe Ijo", category: "Mie", emoji: "🌶️", price: 1, tags: ['masak', 'pedas'], desc: "Warna ijo, aroma cabe ijo asli, pedes seger.", priceRange: "Rp4.000 (Masak Sendiri)" },

    // --- OLAHAN TELUR (MASAK SENDIRI) - EXPANDED ---
    { name: "Telur Dadar", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Simpel, krispi pinggirannya, menu penyelamat.", priceRange: "Rp2.000 (Masak Sendiri)" },
    { name: "Telur Ceplok", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Kuning telur lumer atau matang, selera lo.", priceRange: "Rp2.000 (Masak Sendiri)" },
    { name: "Telur Orak-arik", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Cepet, gampang, tinggal oseng.", priceRange: "Rp2.000 (Masak Sendiri)" },
    { name: "Telur Balado", category: "Lauk", emoji: "🌶️", price: 1, tags: ['masak', 'pedas'], desc: "Pedes manis, temen nasi anget paling pas.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Telur Kecap", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Manis gurih, favorit anak kecil sampe dewasa.", priceRange: "Rp3.000 (Masak Sendiri)" },
    { name: "Telur Crispy", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Telur dadar tepung, kriuknya bikin nagih.", priceRange: "Rp4.000 (Masak Sendiri)" },
    { name: "Telur Setengah Matang", category: "Lauk", emoji: "🥚", price: 1, tags: ['masak', 'sehat'], desc: "Lumer di mulut, protein booster.", priceRange: "Rp2.000 (Masak Sendiri)" },
    { name: "Nasi + Telur + Kecap", category: "Nasi", emoji: "🍛", price: 1, tags: ['masak'], desc: "Menu akhir bulan paling valid.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Telur Gulung", category: "Jajanan", emoji: "🍢", price: 1, tags: ['masak'], desc: "Susah-susah gampang bikinnya, nostalgia SD.", priceRange: "Rp2.000 (Masak Sendiri)" },
    { name: "Telur Pindang", category: "Lauk", emoji: "🥚", price: 1, tags: ['masak', 'sehat'], desc: "Telur rebus coklat motif marmer, bumbu meresap.", priceRange: "Rp3.000 (Masak Sendiri)" },
    { name: "Telur Asin", category: "Lauk", emoji: "🥚", price: 1, tags: ['masak'], desc: "Masir, berminyak, asin gurih.", priceRange: "Rp4.000 (Beli)" },
    { name: "Omelet Mie", category: "Lauk", emoji: "🍕", price: 1, tags: ['masak'], desc: "Pizza-nya anak kos, mie campur telur goreng.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Telur Dadar Padang", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Tebel, pake daun bawang banyak, kelapa sangrai.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Telur Ceplok Pontianak", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Pake kecap asin dan bawang putih goreng, wangi!", priceRange: "Rp3.000 (Masak Sendiri)" },
    { name: "Tamagoyaki (Versi Kosan)", category: "Lauk", emoji: "🍳", price: 1, tags: ['masak'], desc: "Telur dadar gulung manis ala Jepang, pake teflon biasa.", priceRange: "Rp3.000 (Masak Sendiri)" },
    { name: "Telur Kukus", category: "Lauk", emoji: "🍮", price: 1, tags: ['masak', 'sehat'], desc: "Lembut kayak tahu, sehat tanpa minyak.", priceRange: "Rp2.000 (Masak Sendiri)" },

    // --- MASAKAN KOSAN SIMPLE - EXPANDED ---
    { name: "Cah Kangkung", category: "Sayur", emoji: "🥬", price: 1, tags: ['masak', 'sehat'], desc: "Sayur sejuta umat, masak cuma 5 menit.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Sosis & Nugget Goreng", category: "Lauk", emoji: "🌭", price: 1, tags: ['masak'], desc: "Tinggal cemplung minyak, kelar.", priceRange: "Rp10.000 (Masak Sendiri)" },
    { name: "Tumis Sayur Simple", category: "Sayur", emoji: "🥦", price: 1, tags: ['masak', 'sehat'], desc: "Apa aja sayur di kulkas, oseng bawang putih.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Nasi Gila Homemade", category: "Nasi", emoji: "🍛", price: 1, tags: ['masak'], desc: "Sosis, bakso, telur, oseng kecap pedas.", priceRange: "Rp10.000 (Masak Sendiri)" },
    { name: "Sarden Kaleng", category: "Lauk", emoji: "🐟", price: 1, tags: ['masak'], desc: "Tinggal panasin, tambah bawang bombay biar wangi.", priceRange: "Rp10.000 (Masak Sendiri)" },
    { name: "Kornet Goreng", category: "Lauk", emoji: "🥩", price: 1, tags: ['masak'], desc: "Campur telur dikit, goreng garing.", priceRange: "Rp12.000 (Masak Sendiri)" },
    { name: "Tumis Toge Tahu", category: "Sayur", emoji: "🌱", price: 1, tags: ['masak', 'sehat'], desc: "Murah meriah, sehat, protein nabati.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Sayur Sop (Bumbu Racik)", category: "Sayur", emoji: "🍲", price: 1, tags: ['masak', 'sehat'], desc: "Tinggal cemplungin wortel kentang kol, jadi.", priceRange: "Rp7.000 (Masak Sendiri)" },
    { name: "Perkedel Kentang", category: "Lauk", emoji: "🥔", price: 1, tags: ['masak'], desc: "Kentang goreng ulek, celup telur, goreng lagi.", priceRange: "Rp5.000 (Masak Sendiri)" },
    { name: "Tempe Goreng Tepung", category: "Lauk", emoji: "🍘", price: 1, tags: ['masak'], desc: "Mendoan atau kripik, tempe nggak pernah salah.", priceRange: "Rp3.000 (Masak Sendiri)" },

    // --- FANCY / SULTAN (> 100k) - EXPANDED ---
    { name: "Steak Wagyu A5", category: "Western", emoji: "🥩", price: 3, tags: [], desc: "Lemak lumer di mulut, dompet lumer di kasir.", priceRange: "Rp500.000++" },
    { name: "Sushi Premium Omakase", category: "Jepang", emoji: "🍣", price: 3, tags: [], desc: "Duduk manis, biarkan chef beraksi. Mahal? Jelas.", priceRange: "Rp1.500.000++" },
    { name: "Beef Wellington", category: "Western", emoji: "🍖", price: 3, tags: [], desc: "Daging bungkus pastry, ribet bikinnya, mahal belinya.", priceRange: "Rp250.000++" },
    { name: "Lamb Chop", category: "Western", emoji: "🍖", price: 3, tags: [], desc: "Iga domba bakar, empuk, juicy, fancy abis.", priceRange: "Rp150.000++" },
    { name: "Fine Dining Pasta", category: "Western", emoji: "🍝", price: 3, tags: [], desc: "Porsi dikit, piring gede, rasa bintang lima.", priceRange: "Rp150.000++" },
    { name: "Lobster Thermidor", category: "Seafood", emoji: "🦞", price: 3, tags: [], desc: "Lobster keju creamy, definisi makan mewah.", priceRange: "Rp300.000++" },
    { name: "Sashimi Moriawase", category: "Jepang", emoji: "🍱", price: 3, tags: ['sehat'], desc: "Ikan mentah kualitas dewa, fresh banget.", priceRange: "Rp200.000++" },
    { name: "Korean BBQ Premium", category: "Korea", emoji: "🥩", price: 3, tags: [], desc: "Daging sapi marbling tinggi, bakar di meja.", priceRange: "Rp300.000++" },
    { name: "Lobster Bakar Jimbaran", category: "Seafood", emoji: "🦞", price: 3, tags: [], desc: "Bumbu Jimbaran yang manis pedas, asepnya wangi.", priceRange: "Rp250.000++" },
    { name: "Alaskan King Crab", category: "Seafood", emoji: "🦀", price: 3, tags: [], desc: "Kepiting raksasa, dagingnya tebel manis.", priceRange: "Rp1.000.000++" },
    { name: "Caviar & Blinis", category: "Appetizer", emoji: "🐟", price: 3, tags: [], desc: "Telur ikan sturgeon, asin gurih meledak di mulut.", priceRange: "Rp1.500.000++" },
    { name: "Truffle Mushroom Pasta", category: "Western", emoji: "🍄", price: 3, tags: [], desc: "Parutan truffle asli, wanginya semerbak satu ruangan.", priceRange: "Rp200.000++" },
    { name: "Escargot", category: "Appetizer", emoji: "🐌", price: 3, tags: [], desc: "Bekicot Prancis, garlic butter-nya juara.", priceRange: "Rp100.000++" },
    { name: "Pan Seared Foie Gras", category: "Appetizer", emoji: "🦆", price: 3, tags: [], desc: "Hati angsa, lembut kayak mentega, rich banget.", priceRange: "Rp250.000++" },
    { name: "Tomahawk Steak", category: "Western", emoji: "🥩", price: 3, tags: [], desc: "Steak gagang panjang, porsi kuli versi sultan.", priceRange: "Rp1.200.000++" },
    { name: "Sashimi O-Toro", category: "Jepang", emoji: "🍣", price: 3, tags: ['sehat'], desc: "Bagian perut tuna paling berlemak, lumer tanpa dikunyah.", priceRange: "Rp150.000/pcs" },
    { name: "Afternoon High Tea Set", category: "Dessert", emoji: "🫖", price: 3, tags: [], desc: "Ngeteh cantik pake kue-kue mungil di tier.", priceRange: "Rp300.000++" },
    { name: "Private Chef Dinner", category: "Experience", emoji: "👨‍🍳", price: 3, tags: [], desc: "Chef-nya masak di depan muka lo, eksklusif.", priceRange: "Rp2.000.000++" }
];
